# Generated by Django 3.2.4 on 2021-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_avg_rating'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(related_name='user', to='books.Book'),
        ),
    ]
