# Generated by Django 3.2.4 on 2021-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_isbn13'),
        ('users', '0002_user_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommendations',
            field=models.ManyToManyField(related_name='recommended_user', to='books.Book'),
        ),
    ]
