# Generated by Django 3.2.4 on 2021-08-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_genre'),
        ('users', '0003_user_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlisted_user', to='books.Book'),
        ),
    ]
