# Generated by Django 3.2.4 on 2021-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('goodreads_book_id', models.BigIntegerField()),
                ('best_book_id', models.BigIntegerField()),
                ('work_id', models.BigIntegerField()),
                ('books_count', models.IntegerField()),
                ('isbn', models.BigIntegerField()),
                ('isbn13', models.BigIntegerField()),
                ('authors', models.TextField(max_length=510)),
                ('original_publication_year', models.IntegerField()),
                ('original_title', models.TextField()),
                ('title', models.TextField()),
                ('language_code', models.CharField(max_length=10)),
                ('ratings_count', models.IntegerField()),
                ('work_ratings_count', models.IntegerField()),
                ('work_text_reviews_count', models.IntegerField()),
                ('ratings_1', models.IntegerField()),
                ('ratings_2', models.IntegerField()),
                ('ratings_3', models.IntegerField()),
                ('ratings_4', models.IntegerField()),
                ('ratings_5', models.IntegerField()),
                ('image_url', models.TextField()),
                ('small_image_url', models.TextField()),
            ],
        ),
    ]
