# Generated by Django 3.2.4 on 2021-06-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
