# Generated by Django 3.2.4 on 2021-06-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books_book_view',
        ),
    ]
