# Generated by Django 3.2.4 on 2021-06-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
