# Generated by Django 3.2.4 on 2021-07-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='best_book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='books_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='goodreads_book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_3',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_4',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_5',
        ),
        migrations.RemoveField(
            model_name='book',
            name='small_image_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='work_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='work_text_reviews_count',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_publication_year',
            field=models.IntegerField(db_column='publication_year', default=0, max_length=4),
        ),
    ]
